base/urls.py
from django.conf.urls import url
from post import views
from django.views.generic import TemplateView

urlpatterns = [
]

newfolder/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from . import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^title/', include('post.urls', namespace='title')),
    url(r'^base/', include('base.urls', namespace='base')),
    url(r'^stash/', include('stash.urls', namespace='stash')),
    url(r'^post/', include('post.urls', namespace='post')),
    url(r'^comment/', include('comment.urls', namespace='comment')),
    url(r'^info/', include('info.urls', namespace='info')),
    # url(r'^$', TemplateView.as_view(template_name='base.html'))
    url(r'^$', views.AjaxListView.as_view(), name='post_list'),
    url(r'^Main/$', views.searched_list, name='post_list_main'),
    url(r'^articles/search/$', views.search_titles, name='search_titles'),
    url(r'^articles/$', TemplateView.as_view(template_name='artilces.html'))

]

base/models.py
from django.db import models
from title.models import Title
from django.contrib.auth.models import User

# Create your models here.
class Base(models.Model):

    baseUser = models.ForeignKey(User)
    baseTitle = models.ForeignKey(Title)

    baseText = models.TextField(max_length=100)

    baseCreatedAt = models.DateTimeField(auto_now_add=True)
    baseUpdatedAt = models.DateTimeField(auto_now=True)

    basePro = models.PositiveIntegerField(default=0)
    baseCon = models.PositiveIntegerField(default=0)
    baseBlinded = models.SmallIntegerField(default=1)


    def __str__(self):
        return self.baseText

title/models.py
from django.db import models
from django.contrib.auth.models import User



class Title(models.Model):
    titleUser = models.ForeignKey(User)

    titleText = models.TextField(max_length=160, unique=True)

    titleCreatedAt = models.DateTimeField(auto_now_add=True)
    titleUpdatedAt = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.titleText
#
#
# @receiver(post_save, sender=Title)
# def create_contentrelationship(sender, instance, created, **kwargs):
#     if created:
#         ContentRelationship.objects.create(=instance)
#
# @receiver(post_save, sender=Title)
# def save_contentrelationship(sender, instance, **kwargs):
#     instance.contentrelationship.save()

base/views.py
from django.shortcuts import render

# Create your views here.

templates/Main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tit111le</title>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>

</head>
<body>
<div>
    <form id="searchForm" method="get" action="">
    <input type="text" name="q" placeholder="Search posts" />
    <input type="submit" value="Search"/>
    </form>
</div>

<div>
    <form name="demo-form" method="POST" action="">{% csrf_token %}
        <button class="btn btn-success" name="start_manifest">Start Manifest</button>
        <button class="btn btn-success" name="close_manifest">Close Manifest</button>
    </form>
</div>

<div>
    <form>
        <button id="hello" >button</button>
    </form>
</div>


<div>
    {% if title %}
        {% for ss in title %}
            <li>{{ ss.titleText }}</li>
        {% endfor %}
    {% endif %}
</div>

<div id="shuffle">
    <div>1</div>
    <div>2</div>
    <div>3</div>
    <div>4</div>
    <div>5</div>
    <div>6</div>
    <div>7</div>
    <div>8</div>
    <div>9</div>
</div>

<script>
    jQuery(document).ready(function($){
    $('[name="form_internal_manifest"]').on('submit', function(event){
        event.preventDefault();
        $.ajax({
            url : "",
            type : "POST",
            data: {action: 'start_manifest'},
          })
        })
    })

    jQuery(document).ready(function($){
        $('[name="form_internal_manifest"]').on('submit', function(event){
            event.preventDefault();
            $.ajax({
                url : "",
                type : "POST",
                data: {action: 'close_manifest'},
            })
        })
    })

    $(function () {
        var parent = $("#shuffle");
        var divs = parent.children();
        while (divs.length) {
            parent.append(divs.splice(Math.floor(Math.random() * divs.length), 1)[0]);
        }
    });

        $(function () {
        $('#page_2').click(function () {
            $.get('', {page:1}, function (data) {
                console.log('----response-----');
                console.log(data);
                var testnumber = $('#test');

                testnumber.append(data);
            });
            return false;
        });
    });
</script>


</body>
</html>

templates/_base.html
{% for post in title_list %}
    {{ post.titleText }}
{% endfor %}

templates/artilces.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Articles</title>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>

</head>
<body>

<h3>Search</h3>
{% csrf_token %}
<input type="text" id="search" name="search" />

<ul id="search-results">

</ul>
<script>


    jQuery(document).ready(function ($) {
        $('#search').keyup(function () {
            $.ajax({
                type: "POST",
                url : "search/",
                data : {
                    'search_text' : $('#search').val(),
                    'csrfmiddlewaretoken' : $('input[name=csrfmiddlewaretoken]').val()
                },
                success : searchSuccess,
                dataType : 'html'
            });

        });

    });

    function searchSuccess(data, textStatus, jqXHR) {
        $('#search-results').html(data);
    }

</script>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tit111le</title>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>

</head>
<body>
    <a href="#", id="page_2">2p load</a>

<ul>
    {% include '_base.html' %}
</ul>

<div id="test">헬로

</div>

<div id="shuffle">
    <div>1</div>
    <div>2</div>
    <div>3</div>
    <div>4</div>
    <div>5</div>
    <div>6</div>
    <div>7</div>
    <div>8</div>
    <div>9</div>
</div>

<script>
    $(function () {
        $('#page_2').click(function () {
            $.get('', {page:1}, function (data) {
                console.log('----response-----');
                console.log(data);
                var testnumber = $('#test');

                testnumber.append(data);
            });
            return false;
        });
    });

    $(function () {
        var parent = $("#shuffle");
        var divs = parent.children();
        while (divs.length) {
        parent.append(divs.splice(Math.floor(Math.random() * divs.length), 1)[0]);
        }
    });
</script>

</body>
</html>

templates/search.html
{%  if articles.count > 0 %}
    {% for article in articles %}
        <li><a href="/articles/get/{{ article.id }}/">{{ article.titleText }}</a></li>
    {% endfor %}
{% else %}
    <li>None to Show!</li>
{% endif %}